### ISSUE TITLE
Bug on SV_ReadRconUserList

### ISSUE THREAD

**Issue by vincentvegas** [danielepantaleone/ioq3-UrT#6]
Hi Daniele,
i noticed a bug when you allocate memory with a malloc, more precisely in the istruction 
buffer = Z_Malloc(size);
in SV_ReadRconUserList
This happens when you have bot_enable 1 (i still don't understand why) and after a certain number of cyclemap (8 for me).
Error is the following:
----- Server Shutdown (Server fatal crashed: Z_Malloc: failed on allocation of 7468184 bytes from the main zone) -----
Sys_Error: recursive error after: Z_Malloc: failed on allocation of 7468184 bytes from the main zone

**Comment by danielepantaleone** [comment]
Hi, thanks for reporting the issue. I do not have much free time lately but I'll try to provide a fix as soon as I can. 

Inviato da iPhone
