### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by FSBarbatos** [danielepantaleone/ioq3-UrT#9]
Hi,

I think it would be nice to edit your README and add a link somewhere to the engine officially supported by FS from which you copy/pasted tons of commits without any reference. 👍  

Some of the latest examples:
https://github.com/Barbatos/ioq3-for-UrbanTerror-4/commit/deb97989af6a95c5efa24a6a68b3cccd4079eed0
https://github.com/Barbatos/ioq3-for-UrbanTerror-4/commit/299751e416dc98f1a16122983cf9a7b7dd44cb96
https://github.com/Barbatos/ioq3-for-UrbanTerror-4/pull/52

Thanks!

**Comment by danielepantaleone** [comment]
Sure. I ported the commits because people asked me to (even though I didn't test any of the changes). Can you send a PR with the change in the README? I'm going to be out for a month or more so I may forget, but I can accept a PR from my phone.

**Comment by FSBarbatos** [comment]
Thanks!
